# Generated by Django 3.1.5 on 2021-01-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
